"""alteraçao do campo groups da tabela certificado

Revision ID: bbd554afcd31
Revises: 84b77806cb3a
Create Date: 2021-10-12 14:47:00.565810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd554afcd31'
down_revision = '84b77806cb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('certificado_groups_fkey', 'certificado', type_='foreignkey')
    op.create_foreign_key(None, 'certificado', 'groups', ['groups'], ['cod'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificado', type_='foreignkey')
    op.create_foreign_key('certificado_groups_fkey', 'certificado', 'groups', ['groups'], ['id'])
    # ### end Alembic commands ###
